import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { writeFile } from 'node:fs/promises';
import { unwatchFile, watchFile } from 'node:fs';
import { rollup } from 'rollup';
import { nodeResolve } from '@rollup/plugin-node-resolve';
import esbuild from 'rollup-plugin-esbuild';

const currentDir = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(currentDir, '..');
const runtimeEntryPath = resolve(currentDir, '../extension/runtime/injected/main.injected.ts');
const generatedPath = resolve(currentDir, '../extension/runtime/injected/script-runtime.generated.ts');

async function toInjectableFunctionSource(): Promise<{ runtimeSource: string; watchFiles: string[] }> {
  const bundle = await rollup({
    input: runtimeEntryPath,
    plugins: [
      nodeResolve({ browser: true, exportConditions: ['browser', 'default'] }),
      esbuild({
        target: 'es2020',
        minifySyntax: true,
        minifyWhitespace: true,
        tsconfig: false,
      }),
    ],
    treeshake: true,
  });
  const watchFiles = bundle.watchFiles;

  const { output } = await bundle.generate({
    format: 'iife',
    name: '__webCapScriptRuntimeBundle',
    exports: 'named',
    inlineDynamicImports: true,
    compact: true,
  });
  await bundle.close();

  const bundledSource = output[0]?.code ?? '';
  const runtimeSource = `(() => {\n${bundledSource}\nreturn __webCapScriptRuntimeBundle.runScriptRuntime;\n})()`;
  validateInjectableRuntimeSource(runtimeSource);
  return { runtimeSource, watchFiles };
}

function validateInjectableRuntimeSource(runtimeSource: string): void {
  const disallowedPatterns = [
    { pattern: /__name/, label: 'bundler __name helper' },
    { pattern: /import_/, label: 'bundler import helper' },
    { pattern: /^\s*export\s/m, label: 'ES module export statement' },
    { pattern: /^\s*import\s/m, label: 'ES module import statement' },
  ];

  for (const item of disallowedPatterns) {
    if (item.pattern.test(runtimeSource)) {
      throw new Error(`Generated runtime contains ${item.label}.`);
    }
  }
}

async function generateScriptRuntime(): Promise<string[]> {
  const { runtimeSource, watchFiles } = await toInjectableFunctionSource();
  await writeFile(
    generatedPath,
    [
      '// Generated by scripts/generate-script-runtime.ts',
      '// Do not edit manually.',
      `export const scriptRuntimeSource = ${JSON.stringify(runtimeSource)};`,
      '',
    ].join('\n'),
    'utf8',
  );

  console.log(`Generated ${generatedPath}`);
  return watchFiles;
}

const initialWatchFiles = await generateScriptRuntime();

if (process.argv.includes('--watch')) {
  let pending: ReturnType<typeof setTimeout> | undefined;
  const watchedFiles = new Set<string>();
  const scheduleGenerate = () => {
    clearTimeout(pending);
    pending = setTimeout(() => {
      void generateScriptRuntime()
        .then((watchFiles) => updateWatchedFiles(watchFiles))
        .catch((error) => {
          console.error(error);
          process.exitCode = 1;
        });
    }, 50);
  };
  const updateWatchedFiles = (watchFiles: string[]) => {
    const nextWatchedFiles = new Set(
      watchFiles.filter((filePath) => filePath.startsWith(projectRoot) && filePath !== generatedPath),
    );

    for (const filePath of watchedFiles) {
      if (!nextWatchedFiles.has(filePath)) {
        unwatchFile(filePath);
        watchedFiles.delete(filePath);
      }
    }

    for (const filePath of nextWatchedFiles) {
      if (!watchedFiles.has(filePath)) {
        watchFile(filePath, { interval: 250 }, scheduleGenerate);
        watchedFiles.add(filePath);
      }
    }
  };

  updateWatchedFiles(initialWatchFiles);
}
