import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { readFile, writeFile } from 'node:fs/promises';
import { watchFile } from 'node:fs';
import ts from 'typescript';

const currentDir = dirname(fileURLToPath(import.meta.url));
const runtimeSourcePaths = [
  resolve(currentDir, '../extension/runtime/injected/visible-elements.injected.ts'),
  resolve(currentDir, '../extension/runtime/injected/managed-click.injected.ts'),
  resolve(currentDir, '../extension/runtime/injected/script-runtime.injected.ts'),
];
const generatedPath = resolve(currentDir, '../extension/runtime/injected/script-runtime.generated.ts');

function transpileRuntimeModule(source: string): string {
  const transpiled = ts.transpileModule(source, {
    compilerOptions: {
      module: ts.ModuleKind.ESNext,
      target: ts.ScriptTarget.ES2020,
      removeComments: true,
    },
    reportDiagnostics: true,
  });

  const diagnostics = transpiled.diagnostics ?? [];
  if (diagnostics.length > 0) {
    const message = diagnostics
      .map((item) => ts.flattenDiagnosticMessageText(item.messageText, '\n'))
      .join('\n');
    throw new Error(message);
  }

  return transpiled.outputText
    .replace(/^\s*import\s+.+?;\s*$/gm, '')
    .replace(/^export\s+(async\s+function\s+runScriptRuntime)/m, '$1')
    .replace(/^export\s+(function\s+)/gm, '$1')
    .trim();
}

function toInjectableFunctionSource(sources: string[]): string {
  const bundledSource = sources.map((source) => transpileRuntimeModule(source)).join('\n\n');

  if (!bundledSource.includes('async function runScriptRuntime')) {
    throw new Error('Generated runtime did not contain runScriptRuntime.');
  }

  const runtimeSource = `(() => {\n${bundledSource}\nreturn runScriptRuntime;\n})()`;
  validateInjectableRuntimeSource(runtimeSource);
  return runtimeSource;
}

function validateInjectableRuntimeSource(runtimeSource: string): void {
  const disallowedPatterns = [
    { pattern: /__name/, label: 'bundler __name helper' },
    { pattern: /import_/, label: 'bundler import helper' },
    { pattern: /^\s*export\s/m, label: 'ES module export statement' },
    { pattern: /^\s*import\s/m, label: 'ES module import statement' },
  ];

  for (const item of disallowedPatterns) {
    if (item.pattern.test(runtimeSource)) {
      throw new Error(`Generated runtime contains ${item.label}.`);
    }
  }
}

async function generateScriptRuntime(): Promise<void> {
  const sources = await Promise.all(
    runtimeSourcePaths.map((runtimeSourcePath) => readFile(runtimeSourcePath, 'utf8')),
  );
  const runtimeSource = toInjectableFunctionSource(sources);
  await writeFile(
    generatedPath,
    [
      '// Generated by scripts/generate-script-runtime.ts',
      '// Do not edit manually.',
      `export const scriptRuntimeSource = ${JSON.stringify(runtimeSource)};`,
      '',
    ].join('\n'),
    'utf8',
  );

  console.log(`Generated ${generatedPath}`);
}

await generateScriptRuntime();

if (process.argv.includes('--watch')) {
  let pending: ReturnType<typeof setTimeout> | undefined;
  const scheduleGenerate = () => {
    clearTimeout(pending);
    pending = setTimeout(() => {
      void generateScriptRuntime().catch((error) => {
        console.error(error);
        process.exitCode = 1;
      });
    }, 50);
  };

  for (const runtimeSourcePath of runtimeSourcePaths) {
    watchFile(runtimeSourcePath, { interval: 250 }, scheduleGenerate);
  }
}
